### ISSUE TITLE
Cloudinary

### ISSUE THREAD

**Issue by mmallejac** [canonical-web-and-design/canonicalwebteam.blog#139]
Hello team

Using another Wordpress instance is easy with the help of the BLOG_API env. variable.

But I haven't found something similar for Ubuntu's cloudinary image caching mechanism.
It is hardcoded within `logic.py` : `replace_images_with_cloudinary`

Any suggestion to override this ? 

Many thanks,
Michel

**Comment by mmallejac** [comment]
Hello Robin,

With my team we really love all the work you do, generally speaking with Ubuntu (it is our OS for many years now), and in particular with your web site : very nice design, sober and nicely done.

So I've started to look closely at it and I am trying to adapt it to our own needs.  So far so good, especially with the Discourse and Wordpress servers, for the tutorials and blog posts. We also have the same usage, see : 
- https://blog.4next.ch/ 
- https://4next.ch/
- https://tutos.4next.ch/

I am wondering which starting point would be the best : fork the repo at its latest / current state or use the latest (stable ?) release of it ? (the 20.04 release). 

I am not sure that I will be of a great help for you guys in term of contributions, but I'll do what I can.

Many thanks,
Michel :-)

**Comment by nottrobin** [comment]
Thanks for reaching out Michel, and sorry for being slow to respond here. Yes I agree your usage in those sites looks very similar to ours, and it's very gratifying that you like the way we've created these projects.

At the moment our stuff isn't exactly set up that well for use by the community, because we don't have much usage of a lot of it beyond our team, but I do think it's worthwhile making an effort to make it easier for you and others to benefit from.

[Cloudinary](https://cloudinary.com/) isn't actually ours, it's a third party image caching service. But I agree, it shouldn't be required for the use of this module. I'm very happy to try to work out how to make cloudinary optional with you.

If you have ideas about how to do this, please feel free to file a pull request to this project, or I'll try to get to looking into how to do it in the next few days.

**Comment by mmallejac** [comment]
Great ! Many thanks for taking the time to answer me. I'll see what I can do for the Cloudinary stuff.

**Comment by jpmartinspt** [comment]
@mmallejac Just to be clear do you want to do any formatting to your blog posts links or is it enough to be able to disable the cloudinary?

**Comment by mmallejac** [comment]
Hello @jpmartinspt ,
Just disable the cloudinary prefixing would be great.
Thanks a lot !

**Comment by mmallejac** [comment]
Great, many thanks to all guys :-) will test that soon

**Comment by albertkol** [comment]
Hey @mmallejac

To finally get back to you...

As of version 6.1.1, you have the option to turn off the Cloudinary URL conversions by doing this:

```python
blog = build_blueprint(
    BlogViews(
        api=BlogAPI(
          session=session, 
          use_image_template=False,
        ),
    )
)

```

That will prevent article images from using the Cloudinary prefix.

Also if you choose to use the suggested views mentioned in the `README.md` for your blog, be aware that `blog-card.html` uses Cloudinary by default. You will just need to remove that.

**Comment by mmallejac** [comment]
Many thanks, I'll check that after vacations.

**Comment by mmallejac** [comment]
Hello Canonical,

It took me a while to come back to this project. 
A big Tank You for this change in your code, it works just fine !

Michel
